### ISSUE TITLE
Removing first 7 cards without studying new cards

### ISSUE THREAD

**Issue by jantznick** [boolbag/Anki-Goodies#1]
Hopefully this is the right way to leave a comment via github, didn't see another way.

First off, thank you for this deck, it is exactly what I've been looking for for years!!

Here is my question, which seems to be more about anki than about the deck. I understand that the first 7 cards are a primer to what this deck is about, but is there a way to remove them without screwing up the learning method mentioned on your site?
I went to custom study, add 7 cards for today. Then when I went through them and suspended them, anki was acting like I didn't actually review them, it went ahead and just added 7 cards of actual verb study. So now the method of going through the first 58 tomorrow is off because I already seem to be studying the first 7.

I've found a way around this by opening up in the desktop app and suspending via the browse tab, but still, a weird way for anki to do things it seems if using the deck this way.

**Comment by wyohm** [comment]
Anki doesn't count a card as reviewed unless you actually review it by pressing "good", "easy", "hard"... If you suspend, bury, or otherwise skip a card it will choose a new card for you to review until you reach your new card goal. So your "mistake" was to "Increase today's new card limit" when you didn't actually want to review any cards. Fortunately, that count resets each day and you want to start tomorrow, so you can choose the appropriate number tomorrow. I believe you can use a negative number in "Increase today's new card limit" if you want to make that go away now.

I find it easier to use the tags rather increasing the new card limit. Go to your deck, "Custom Study", select "Study by card state or tag" and "new cards only", then "Choose Tags". Choose the required tag for the verb you want to start with ("avere" for Italian or "ser" for Spanish) and go. Later, you can find the tag for the next verb in the browser. These instructions are for the desktop version, but I believe the mobile version should be similar.
